### PR TITLE
ffmpeg 4.2.3

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by retokromer** [comment]
It’s not clear to my why `linuxbrew/xorg/libxext` is called. Should it not be `linuxbrew/xorg/libxv`?

**Comment by retokromer** [comment]
Still same error. `libxext` is **not** part of the [Linuxbrew Xorg Provided Formulae](https://github.com/Linuxbrew/homebrew-xorg#provided-formulae).

**Comment by retokromer** [comment]
@slhck Do you have any clue?

**Comment by slhck** [comment]
Haven't seen this PR yet, somehow I didn't get notifications. I will look at it in the coming days. I'm not sure if we shouldn't fix the CI script overall given the issues we've had in the other PR? I will check.

**Comment by retokromer** [comment]
No problem! I guess @michaelni is releasing the version 4.3 and as soon it’s done I’ll upgrade here as well.

**Comment by scribblemaniac** [comment]
> Still same error. libxext is not part of the Linuxbrew Xorg Provided Formulae.

I would like to point out that libxext **is** in the list you've linked, and does have a formula in that repo. I'm not sure why it isn't finding and tapping that automatically, that seems like something that linuxbrew should do, but the obvious potential workaround would just be to run `brew tap linuxbrew/xorg` before installing the formula.

**Comment by retokromer** [comment]
Thank you for your information, @scribblemaniac! I don’t know why I didn’t see `libxext` when I checked… It should not be necessary to tap explicitly before since quite a while. I’ll check again locally.

**Comment by retokromer** [comment]
Now _Travis CI - Branch_ passes without any change…

**Comment by retokromer** [comment]
@slhck I added an useless commit and now it passed…

**Comment by slhck** [comment]
So a force-push didn't trigger a rebuild? I'm not an expert on Travis either – I'll investigate this and try another build script.

Feel free to merge!

**Pull request merged**
