### PR TITLE
revision bump

### PR DESCRIPTION
**Pull request by retokromer**
should resolve https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/20

### CODE REVIEW

**Comment by slhck** [comment]
I cannot merge this (just on a mobile phone and failing CI prevents that), but please go ahead.
I will look at the CI later.

**Comment by slhck** [comment]
Hmm.

```
homebrew-ffmpeg/ffmpeg/ffmpeg:
  * 'revision 2' should be removed
Error: 1 problem in 1 formula detected
```

This is what `brew audit` says. I am not sure why though.

**Comment by retokromer** [comment]
Hmm… locally the error is not generated and `brew audit --strict` exits with a `0`. I will try to understand it. The goal is just to force recompilation with the new version of X.265.

**Comment by retokromer** [comment]
I cannot understand what Travis is complaining about, therefore closing.

**Comment by slhck** [comment]
FWIW, I asked here what it means: https://discourse.brew.sh/t/what-does-revision-2-should-be-removed-mean-in-brew-audit/7782

**Comment by retokromer** [comment]
Locally, forcing the re-compilation resolves the problem…

I personally don’t think the hint from the audit is accurate: I think the revision cannot be deleted completely: the 1<sup>st</sup> should stay, in my opinion.

**Comment by slhck** [comment]
Yes, either 1 should stay, or we would have to release a completely new version of ffmpeg. Anything else doesn't make sense, but I cannot make sense of the `brew audit` source code either, as the function handling this part is not documented at all and makes use of several helper functions that I cannot decipher within the few minutes I want so spend on it ;)

**Comment by retokromer** [comment]
Let’s wait and see if there is an answer to your question on the forum.

**Comment by retokromer** [comment]
@slhck I saw the discussion in the forum. Is this correct?

https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/blob/3a4c6426ea532635050248fd03f64dc179b6d4e4/.travis.yml#L33

Should it not be:

```ruby
brew update && brew update 
```

or am I missing something?

**Comment by slhck** [comment]
I got this from another project, and I suppose the idea was to try to update once more if it fails. It should not be necessary though. I will have to improve the CI config and see if it can be simplified.

**Comment by retokromer** [comment]
Revision bump made in https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/pull/23

**Pull request closed without merging**
