### PR TITLE
Add travis test file

### PR DESCRIPTION
**Pull request by slhck**

### CODE REVIEW

**Comment by slhck** [comment]
@retokromer Do you have an idea why `brew install` fails with a nonzero exit code here? AFAICT everything is installed just fine.

Job log here: https://travis-ci.com/homebrew-ffmpeg/homebrew-ffmpeg/jobs/277861578

**Comment by scribblemaniac** [comment]
If I may join in, it's not not all fine: https://travis-ci.com/homebrew-ffmpeg/homebrew-ffmpeg/jobs/277861578#L631-L634. It's probably trying to fetch changes with git from homebrew-ffmpeg in the taps directory. I wouldn't mess with any of that taps stuff for the CI; just install the formula files directly. Something like: `brew install -v $TRAVIS_BUILD_DIR/Formula/*.rb`.

**Comment by slhck** [comment]
Thanks for the hint. I may try this, but all other Travis configs I saw for taps were using exactly this approach of symlinking the PWD into the Taps directory.

Note that the Linux job runs fine — it's only the macOS job that exhibits this problem.

Apparently it's trying to fetch only upon first installation. Is there any way to make it not do that? I'm trying now with `HOMEBREW_NO_AUTO_UPDATE` set — it was previously only set in the Linux part.

**Comment by retokromer** [comment]
@slhck I am out of office and can delve into this only during the weekend. Sorry for that! (Also I am not a Travis guru at all.)

**Comment by slhck** [comment]
No worries. I'm not a guru either, just trying to figure out what is going wrong. Now I see this: https://travis-ci.com/homebrew-ffmpeg/homebrew-ffmpeg/jobs/278112390#L944

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink Frameworks/Python.framework/Headers
Target /usr/local/Frameworks/Python.framework/Headers
is a symlink belonging to python@2. You can unlink it:
  brew unlink python@2
```

I'm not sure why it'd install python@2 to begin with, but I'll investigate.

**Comment by slhck** [comment]
Seems to work now. It does not test the formula options, but we can add this at a later point in time.

**Comment by retokromer** [comment]
Excellent, thanks a lot!

**Pull request merged**
