### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by slhck**
Mention which versions we support

### CODE REVIEW

**Review by retokromer — APPROVED** [review]

**Comment by retokromer** [comment]
We should switch from travis to github-actions.

**Comment by slhck** [comment]
I haven't worked with GH Actions before … I can of course remove Travis, but from what I see, the GH Actions never really succeeded before?

**Comment by retokromer** [comment]
I’ll try to find the time to give a look next weekend. (It’s currently labeled as “build error” on the main page.)

**Comment by retokromer** [comment]
Sorry, I didn’t find the time during the weekend…

**Pull request merged**
