### PR TITLE
[WIP] add libplacebo

### PR DESCRIPTION
**Pull request by retokromer**
Works well locally on my end, but I guess, we should wait until https://github.com/Homebrew/homebrew-core/pull/126408 by @ahobsonsayers is pushed.

### CODE REVIEW

**Comment by retokromer** [comment]
🤣🤣🤣

>Error: homebrew-ffmpeg/ffmpeg/ffmpeg contains a recursive dependency on itself:
>homebrew-ffmpeg/ffmpeg/ffmpeg depends on itself via libplacebo

Indeed, we need to wait.

**Comment by retokromer** [comment]
The official Homebrew formula has been released today, but the upstream recursive dependency (libplacebo) is not yet resolved.

**Comment by ahobsonsayers** [comment]
Yeah sorry about that @retokromer, I'm hitting a bit of a brick wall with it and need to find some time to dedicate to actually learning about the details C++ compilation and CMake in more depth to solve the issue (im a Python/JS/Go guy sadly!). I do actually have it working with your branch and my libplacebo formula on my machine, but you do have to manually unlink first.

If there are any updated, i will post again here.

**Comment by ahobsonsayers** [comment]
This PR removing the FFmpeg dependancy has now been merged https://github.com/Homebrew/homebrew-core/pull/132349 thus fixing the circular dependancy 🎉 

This being said, libplacebo will not work properly (at least in my testing) until shaderc is added as a dependancy as well. This is being tackled here https://github.com/Homebrew/homebrew-core/pull/132171

I think it is worth waiting until that PR is merged before we merge this one.

**Comment by retokromer** [comment]
Closing this, because (after 30 days) I cannot run again the tests, in order to check if now the upstream issues are resolved.

**Pull request closed without merging**
