### PR TITLE
update to FFmpeg 7.0

### PR DESCRIPTION
**Pull request by retokromer**
in addition, supersedes #152 #153 #154 and #158

### CODE REVIEW

**Comment by retokromer** [comment]
@slhck I don’t know how to resolve the cyclic dependency.

**Comment by slhck** [comment]
Me neither! We've had that before: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/13 — and the resolution always consisted of uninstalling ffmpeg first, then installing chromaprint, then ffmpeg again. This is also what caused previous PRs to fail. I posted in Homebrew discussions to get some help, I really don't know. Maybe a Homebrew maintainer has a solution.

https://github.com/orgs/Homebrew/discussions/5264

**Comment by retokromer** [comment]
Thank you!

**Comment by retokromer** [comment]
Using the [workaround](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg?tab=readme-ov-file#troubleshooting), the installation still completes correctly and a test works on my end.

**Comment by slhck** [comment]
Yeah, the particular build failure has nothing to do with this, so if you want please merge!

**Pull request merged**
