### PR TITLE
FFmpeg 6.0

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by slhck** [comment]
Triggering CI run again because it fails due to some obscure error.

**Comment by retokromer** [comment]
@slhck I could not reproduce locally: on my end it works fine on both Debian 11.6 (Intel) and macOS 12.6.3 (ARM).

**Comment by slhck** [comment]
Seems to be a path mismatch? I am not sure. I asked here: https://github.com/Homebrew/discussions/discussions/4282

In any case, if it works for you, please do the merge!

I know there are some dependent formulas on homebrew-core but that doesn't interfere with our use case.

**Comment by slhck** [comment]
Merged after fixing CI!

**Comment by retokromer** [comment]
Oh, thank you, you were quicker!

**Pull request merged**
