### PR TITLE
fix chromaprint

### PR DESCRIPTION
**Pull request by retokromer**
Should fix https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/13

### CODE REVIEW

**Comment by slhck** [comment]
LGTM, let's see what Travis says.

I had not seen the bug report initially since I was not subscribed to this repo. Thanks for handling this.

**Comment by retokromer** [comment]
@slhck FYI: Now it works locally on my end.

**Comment by Rogue-Git-Dev** [comment]
This fixed it. Initially, I installed using
> brew install homebrew-ffmpeg/ffmpeg/ffmpeg --HEAD $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)
which installed version 4.3-with-options_2. I know not what _2 denotes, but it is different from the 4.3-with-options_1 [what does _1 denote?] when I installed without any arguments upon acquisition of the tap. Execution of the command above did not produce the issue of recursion.

To know if the problem is truly solved, I uninstalled that and reinstalled using the command
> brew install homebrew-ffmpeg/ffmpeg/ffmpeg --HEAD --with-chromaprint --with-decklink --with-fdk-aac --with-game-music-emu --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvmaf --with-libxml2 --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-openssl@1.1 --with-rav1e --with-rtmpdump --with-rubberband --with-speex --with-srt --with-tesseract --with-two-lame --with-wavpack --with-webp --with-xvid --with-zeromq --with-zimg
which did not produce the issue of recursion as did previously.

**Comment by retokromer** [comment]
@Rogue-Git-Dev Thank you for reporting back!

>which installed version 4.3-with-options_2. I know not what _2 denotes, but it is different from the 4.3-with-options_1 [what does _1 denote?]

`_1` is the revision 1 of this version and `_2` revision 2.

**Comment by Rogue-Git-Dev** [comment]
Oh right. The -with-options betwixt the version and the revision confused me. If it read 4.3_x-with-options, that would make more sense to me.

**Comment by retokromer** [comment]
I agree, yet that’s the way FFmpeg and Brew work together…

**Pull request merged**
